version: 0.2
phases:
  install:
    commands:
    - npm i
    - aws cloudformation package --template-file template.yaml --s3-bucket awsdrstnp-cai-serverless-cf-builds --output-template-file outputSamTemplate.yaml
  build:
    commands:
    - npm test
artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml